name: Node.js Release 

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global user.name "GitHub Action CI"
    - run: git config --global user.email "user@example.org"
    - run: npm install
    - run: npx @grafana/sign-plugin@1.0.3
      env:
        GRAFANA_API_KEY: ${{ eyJrIjoiazlYOVRuV3ZiUGxrTFZFRHZKNHJuSk9PV0RzMVVlSDEiLCJuIjoiYnV0dG9uLWt5a2xvcyIsImlkIjoxfQ== }}
    - run: npm run release -- patch --ci -VV
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GRAFANA_API_KEY: ${{ eyJrIjoiazlYOVRuV3ZiUGxrTFZFRHZKNHJuSk9PV0RzMVVlSDEiLCJuIjoiYnV0dG9uLWt5a2xvcyIsImlkIjoxfQ== }}
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: button-kyklos-digro.zip
        path: button-kyklos-digro.zip
